# rpmrebuild autogenerated specfile

BuildRoot: /root/.tmp/rpmrebuild.8234/work/root
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    ip-10-8-105-156
#BUILDTIME:    Sun Mar  4 00:57:38 2018
#SOURCERPM:    hadoop_2_6_1_0_129-2.7.3.2.6.1.0-129.src.rpm

#RPMVERSION:   4.11.3



#OS:           linux
#SIZE:           244699786
#ARCHIVESIZE:           244725720
#ARCH:         x86_64
BuildArch:     x86_64
Name:          hadoop_2_6_1_0_129
Version:       2.7.3.2.6.1.0
Release:       129
License:       Apache License v2.0
Group:         Development/Libraries
Summary:       Hadoop is a software platform for processing vast amounts of data
Distribution:  Amazon Linux AMI

URL:           http://hadoop.apache.org/core/







Provides:      libhadoop.so.1.0.0()(64bit)
Provides:      libsnappy.so.1()(64bit)
Provides:      hadoop_2_6_1_0_129 = 2.7.3.2.6.1.0-129
Provides:      hadoop_2_6_1_0_129(x86-64) = 2.7.3.2.6.1.0-129
Requires:      coreutils
Requires:      /usr/sbin/useradd
Requires:      /usr/sbin/usermod
Requires:      /sbin/chkconfig
Requires:      /sbin/service
Requires:      zookeeper_2_6_1_0_129 >= 3.4.0
Requires:      ranger_2_6_1_0_129-hdfs-plugin
Requires:      ranger_2_6_1_0_129-yarn-plugin
Requires:      hdp-select >= 2.6.1.0-129
Requires:      spark_2_6_1_0_129-yarn-shuffle
Requires:      spark2_2_6_1_0_129-yarn-shuffle
Requires:      psmisc
Requires:      nc
Requires:      sh-utils
Requires:      redhat-lsb-core
Requires:      /bin/sh
Requires:      /bin/sh
Requires:      /bin/sh
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#suggest
#enhance
%description
Hadoop is a software platform that lets one easily write and
run applications that process vast amounts of data.

Here's what makes Hadoop especially useful:
* Scalable: Hadoop can reliably store and process petabytes.
* Economical: It distributes the data and processing across clusters
              of commonly available computers. These clusters can number
              into the thousands of nodes.
* Efficient: By distributing the data, Hadoop can process it in parallel
             on the nodes where the data is located. This makes it
             extremely rapid.
* Reliable: Hadoop automatically maintains multiple copies of data and
            automatically redeploys computing tasks based on failures.

Hadoop implements MapReduce, using the Hadoop Distributed File System (HDFS).
MapReduce divides applications into many small blocks of work. HDFS creates
multiple replicas of data blocks for reliability, placing them on compute
nodes around the cluster. MapReduce can then process the data where it is
located.
%files
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/bash_completion.d/hadoop"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/default/hadoop"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/capacity-scheduler.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/configuration.xsl"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/container-executor.cfg"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/core-site.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-env.cmd"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-env.sh"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-metrics.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-metrics2.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-policy.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-acls.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-env.sh"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-log4j.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-site.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/log4j.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/mapred-env.cmd"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/mapred-env.sh"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/mapred-queues.xml.template"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/mapred-site.xml.template"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/slaves"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/ssl-client.xml.example"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/ssl-server.xml.example"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/yarn-env.cmd"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/azure-data-lake-store-sdk-2.1.4.jar"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/hadoop"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/hadoop-fuse-dfs"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/hadoop.distro"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/hdfs"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/mapred"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/rcc"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/bin/yarn"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/conf"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/etc"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/etc/hadoop"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-annotations-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-annotations.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-auth-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-auth.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-aws-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-aws.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-azure-2.7.3.2.6.1.0-129.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-azure-datalake-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-azure-datalake.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-azure.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-common-2.7.3.2.6.1.0-129-tests.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-common-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-common-tests.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-common.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-nfs-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/hadoop-nfs.jar"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/activation-1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/apacheds-i18n-2.0.0-M15.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/apacheds-kerberos-codec-2.0.0-M15.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/api-asn1-api-1.0.0-M20.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/api-util-1.0.0-M20.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/asm-3.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/avro-1.7.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/aws-java-sdk-core-1.10.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/aws-java-sdk-kms-1.10.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/aws-java-sdk-s3-1.10.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/azure-keyvault-core-0.8.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/azure-storage-4.2.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-beanutils-1.7.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-beanutils-core-1.8.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-cli-1.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-codec-1.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-collections-3.2.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-compress-1.4.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-configuration-1.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-digester-1.8.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-io-2.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-lang-2.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-lang3-3.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-logging-1.1.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-math3-3.1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/commons-net-3.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/curator-client-2.7.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/curator-framework-2.7.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/curator-recipes-2.7.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/gson-2.2.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/guava-11.0.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/hamcrest-core-1.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/htrace-core-3.1.0-incubating.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/httpclient-4.5.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/httpcore-4.4.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-annotations-2.2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-core-2.2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-core-asl-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-databind-2.2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-jaxrs-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-mapper-asl-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jackson-xc-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/java-xmlbuilder-0.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jaxb-api-2.2.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jaxb-impl-2.2.3-1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jcip-annotations-1.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jersey-core-1.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jersey-json-1.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jersey-server-1.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jets3t-0.9.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jettison-1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jetty-6.1.26.hwx.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jetty-sslengine-6.1.26.hwx.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jetty-util-6.1.26.hwx.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/joda-time-2.9.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jsch-0.1.54.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/json-smart-1.1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jsp-api-2.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/jsr305-3.0.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/junit-4.11.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/log4j-1.2.17.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/mockito-all-1.8.5.jar"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadoop.a"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadoop.so"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadoop.so.1.0.0"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadooppipes.a"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadooputils.a"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhdfs.a"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libsnappy.so"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libsnappy.so.1"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/native/libsnappy.so.1.1.4"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/netty-3.6.2.Final.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/nimbus-jose-jwt-3.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/paranamer-2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/protobuf-java-2.5.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/servlet-api-2.5.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/slf4j-api-1.7.10.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/slf4j-log4j12-1.7.10.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/snappy-java-1.0.4.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/stax-api-1.0-2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/xmlenc-0.52.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/xz-1.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/lib/zookeeper-3.4.6.2.6.1.0-129.jar"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-config.cmd"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-config.sh"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-layout.sh"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/hdfs-config.cmd"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/kms-config.sh"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/mapred-config.cmd"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/yarn-config.cmd"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/man"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/man/man1"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/man/man1/hadoop.1.gz"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop/mapreduce.tar.gz"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/sbin"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/sbin/hadoop-daemon.sh"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/sbin/hadoop-daemons.sh"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/sbin/slaves.sh"
%pre -p /bin/sh
getent group hadoop >/dev/null || groupadd -r hadoop
%post -p /bin/sh
if [ !  -e "/etc/hadoop/conf" ]; then
    rm -f /etc/hadoop/conf
    mkdir -p /etc/hadoop/conf
    cp -rp /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/* /etc/hadoop/conf
fi
/usr/bin/hdp-select --rpm-mode set hadoop-client 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-datanode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-journalnode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-nfs3 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-namenode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-portmap 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-secondarynamenode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-zkfc 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-mapreduce-historyserver 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-yarn-resourcemanager 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-yarn-nodemanager 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-yarn-timelineserver 2.6.1.0-129
%changelog